---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reflector.bizcochillo.io
  resources:
  - nodeportreflectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reflector.bizcochillo.io
  resources:
  - nodeportreflectors/finalizers
  verbs:
  - update
- apiGroups:
  - reflector.bizcochillo.io
  resources:
  - nodeportreflectors/status
  verbs:
  - get
  - patch
  - update
