apiVersion: reflector.bizcochillo.io/v1alpha1
kind: NodePortReflector
metadata:
  labels:
    app.kubernetes.io/name: hcp-nodeport-reflector
    app.kubernetes.io/managed-by: kustomize
  name: nodeportreflector-sample
spec:
  headless: true # Uncomment to create a Headless Service (ClusterIP: None) without a VIP
  hostedCluster:
    name: my-cluster
    namespace: clusters
  targetService:
    name: my-backend
    namespace: default
